# Generated by Django 5.2.1 on 2026-06-02 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='layanan',
            name='deskripsi_singkat',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layanan',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesankontak',
            name='bidang_usaha',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pesankontak',
            name='layanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tms.layanan'),
        ),
        migrations.AddField(
            model_name='pesankontak',
            name='perusahaan',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pesankontak',
            name='pesan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesankontak',
            name='telepon',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='FiturLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitur', to='tms.layanan')),
            ],
        ),
    ]
