# Generated by Django 5.2.1 on 2026-06-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_layanan_aktif_layanan_deskripsi_singkat_layanan_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='layanan/'),
        ),
    ]
