# Generated by Django 5.2.1 on 2026-06-22 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tms", "0003_layanan_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneDriveLoginURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("deskripsi", models.TextField(blank=True)),
                ("aktif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OneDrive Login URL",
                "verbose_name_plural": "OneDrive Login URLs",
            },
        ),
        migrations.CreateModel(
            name="ProfilPerusahaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_perusahaan",
                    models.CharField(default="Tri Master Solusindo", max_length=200),
                ),
                (
                    "foto_perusahaan",
                    models.ImageField(blank=True, null=True, upload_to="profil/"),
                ),
                (
                    "foto_struktur_organisasi",
                    models.ImageField(blank=True, null=True, upload_to="profil/"),
                ),
                ("deskripsi_singkat", models.TextField(blank=True, max_length=500)),
                ("alamat", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telepon", models.CharField(blank=True, max_length=20)),
                ("nomor_wa", models.CharField(blank=True, max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profil Perusahaan",
                "verbose_name_plural": "Profil Perusahaan",
            },
        ),
        migrations.CreateModel(
            name="OrderLayanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("nomor_wa", models.CharField(max_length=20)),
                ("pesan", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("diproses", "Diproses"),
                            ("selesai", "Selesai"),
                            ("dibatalkan", "Dibatalkan"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="tms.layanan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PengaturanSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("canonical_url", models.URLField(blank=True)),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.TextField(blank=True)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layanan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_settings",
                        to="tms.layanan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengaturan SEO",
                "verbose_name_plural": "Pengaturan SEO",
            },
        ),
        migrations.CreateModel(
            name="TemplateWhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_template", models.CharField(max_length=200)),
                ("isi_template", models.TextField()),
                ("aktif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_templates",
                        to="tms.layanan",
                    ),
                ),
            ],
            options={
                "ordering": ["layanan", "nama_template"],
            },
        ),
    ]
